#define _POSIX_C_SOURCE 200809L
#include <X11/Xft/Xft.h>
#include <X11/Xlib.h>
#include <fontconfig/fontconfig.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

#include "container.h"
#include "drw.h"
#include "input.h"
#include "module.h"
#include "panel.h"
#include "panel_globals.h"
#include "settings.h"

#define MAX_LINES 64
#define MENU_SCRIPT "/home/swaminsane/.local/bin/menu/khalmenu"
#define CALLOG "/home/swaminsane/.local/bin/callog"
#define LOG_FILE "/.local/share/cal.log"

typedef struct {
  char lines[MAX_LINES][256];
  int nlines;
  int btn_sync[2];       /* module‑relative x range for [Sync] */
  time_t pending_reload; /* 0 = none, else load events when timer fires */
} CalState;

/* ── load the log file generated by callog ─────────── */
static void load_events(CalState *s) {
  s->nlines = 0;

  const char *home = getenv("HOME");
  if (!home)
    return;
  char path[512];
  snprintf(path, sizeof(path), "%s%s", home, LOG_FILE);

  FILE *f = fopen(path, "r");
  if (!f)
    return;

  char line[256];
  while (fgets(line, sizeof(line), f) && s->nlines < MAX_LINES) {
    line[strcspn(line, "\n")] = '\0';
    if (line[0] == '\0')
      continue;
    strncpy(s->lines[s->nlines], line, sizeof(s->lines[0]) - 1);
    s->nlines++;
  }
  fclose(f);
}

/* ── module callbacks ──────────────────────────────── */
static void cal_init(Module *m, int x, int y, int w, int h) {
  (void)x;
  (void)y;
  m->w = w;
  m->h = h;
  CalState *s = calloc(1, sizeof(CalState));
  m->priv = s;
  load_events(s);
}

static void cal_draw(Module *m, int x, int y, int w, int h, int focused) {
  (void)focused;
  CalState *s = (CalState *)m->priv;

  /* card background + border */
  XSetForeground(dpy, drw->gc, scheme[2][ColBg].pixel);
  XFillRectangle(dpy, drw->drawable, drw->gc, x, y, w, h);
  XSetForeground(dpy, drw->gc, scheme[0][ColBorder].pixel);
  XDrawRectangle(dpy, drw->drawable, drw->gc, x, y, w - 1, h - 1);

  int pad = MODULE_PADDING;
  int font_h = drw->fonts->h;

  /* header */
  drw_setscheme(drw, scheme[1]); /* accent fg */
  const char *header = "Planned events";
  int header_w = drw_fontset_getwidth(drw, header);
  int header_y = y + pad;
  drw_text(drw, x + pad, header_y, header_w, font_h, 0, header, 0);

  /* [Sync] button – right‑aligned */
  const char *sync_label = "[Sync]";
  int sync_w = drw_fontset_getwidth(drw, sync_label);
  int sync_x = x + w - pad - sync_w;
  drw_text(drw, sync_x, header_y, sync_w, font_h, 0, sync_label, 0);
  s->btn_sync[0] = sync_x - x;
  s->btn_sync[1] = sync_x + sync_w - x;

  /* event / log area */
  int list_y = header_y + font_h + 4;
  int list_h = h - 2 * pad - font_h - 8;
  int max_lines = list_h / font_h;
  if (max_lines > s->nlines)
    max_lines = s->nlines;
  if (max_lines < 0)
    max_lines = 0;

  if (s->nlines == 0) {
    drw_setscheme(drw, scheme[0]);
    const char *msg = "No events";
    int tw = drw_fontset_getwidth(drw, msg);
    drw_text(drw, x + (w - tw) / 2, list_y + (list_h - font_h) / 2, tw, font_h,
             0, msg, 0);
    return;
  }

  drw_setscheme(drw, scheme[0]);
  for (int i = 0; i < max_lines; i++) {
    int ly = list_y + i * font_h;
    drw_text(drw, x + pad, ly, w - 2 * pad, font_h, 0, s->lines[i], 0);
  }
}

/* ── input handler ─────────────────────────────────── */
static void cal_input(Module *m, const InputEvent *ev) {
  CalState *s = (CalState *)m->priv;
  if (ev->type != EV_PRESS || ev->button != Button1)
    return;

  int rel_x = ev->x, rel_y = ev->y;
  int pad = MODULE_PADDING;
  int font_h = drw->fonts->h;

  /* [Sync] button */
  if (rel_y >= pad && rel_y < pad + font_h) {
    if (rel_x >= s->btn_sync[0] && rel_x < s->btn_sync[1]) {
      /* 1. sync → 2. update log → 3. reload after 2s */
      if (fork() == 0) {
        setsid();
        execl("/bin/sh", "/bin/sh", "-c", "vdirsyncer sync && " CALLOG, NULL);
        _exit(1);
      }
      s->pending_reload = time(NULL) + 2; /* reload soon */
      return;
    }
  }

  /* any other click → open khalmenu (no automatic log update) */
  if (fork() == 0) {
    setsid();
    execl("/bin/sh", "/bin/sh", "-c", MENU_SCRIPT, NULL);
    _exit(1);
  }
  /* the timer will eventually refresh; no forced reload */
}

/* ── timer ─────────────────────────────────────────── */
static void cal_timer(Module *m) {
  static time_t last_refresh = 0;
  time_t now = time(NULL);

  CalState *s = (CalState *)m->priv;

  /* pending reload after sync */
  if (s->pending_reload > 0 && now >= s->pending_reload) {
    s->pending_reload = 0;
    load_events(s);
    panel_redraw();
  }

  /* regular refresh every 30 s */
  if (now - last_refresh >= 30) {
    last_refresh = now;
    load_events(s);
    panel_redraw();
  }
}

static void cal_destroy(Module *m) { free(m->priv); }

static LayoutHints *cal_hints(Module *m) {
  (void)m;
  static LayoutHints hints = {
      .min_h = 144,
      .pref_h = 144,
      .max_h = 144,
      .expand_y = 0,
      .expand_x = 1,
  };
  return &hints;
}

Module calendar_module = {
    .name = "calendar",
    .init = cal_init,
    .draw = cal_draw,
    .input = cal_input,
    .timer = cal_timer,
    .destroy = cal_destroy,
    .get_hints = cal_hints,
    .margin_top = 4,
    .margin_bottom = 4,
    .margin_left = 0,
    .margin_right = 0,
    .theme = (ContainerTheme *)&module_card_theme,
};

void __attribute__((constructor)) calendar_register(void) {
  register_module(&calendar_module);
}
